modLoader="javafml" 
loaderVersion="[37,)"
license="MIT"
[[mods]]
modId="trackapi" 
version="1.2" 
displayName="TrackAPI" 
authors="cam72cam" 
description='''A common track interface for minecraft forge'''
[[dependencies.trackapi]] 
    modId="forge" 
    mandatory=true 
    versionRange="[37,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.trackapi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
