modLoader="javafml"
loaderVersion="[2,)"
license="MIT"
[[mods]]
modId="trackapi" 
version="1.3"
displayName="TrackAPI" 
authors="cam72cam" 
description='''A common track interface for neoforge'''
[[dependencies.trackapi]] 
    modId="neoforge"
    type='required'
    versionRange="[21.1.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.trackapi]]
    modId="minecraft"
    type='required'
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
