name: TrackAPI CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                ref=`echo ${github_ref} | sed -e 's,refs/heads/,,' | tr '/' '-'`
                echo $ref
                echo "::set-env name=ref::$ref"
              env:
                github_ref: ${{ github.ref }}
                ACTIONS_ALLOW_UNSECURE_COMMANDS: true
            - name: keyscan
              run: mkdir -p ~/.ssh/ && ssh-keyscan -t rsa teamopenindustry.cc >> ~/.ssh/known_hosts
            - name: Gradle publish
              env:
                MAVENCI_PASS: ${{ secrets.MAVENCI_PASS }}
              run: ./gradlew publish
